# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            Ulises Genis-Cuevas
tagline:          'tagline?'
description:      'Esta es la descripción'
url:              https://ugenis7.github.io/
baseurl:          /

author:
  name:           'Ulises Genis Cuevas'
  url:            https://twitter.com/ugenis7

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/ugenis7
