# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:               Ulises Genis
tagline:             Blog personal
url:                 https://ugenis7.github.io
paginate:            2
baseurl:             "https://ugenis7.github.io/poole/"

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _sass
  style:            :compressed

# About/contact
author:
  name:              Ulises Genis
  url:               https://twitter.com/ugenis7
