# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            Blog Personal
tagline:          'tagline?'
description:      'Blog Personal de Ulises Genis Cuevas'
url:              https://ugenis7.github.io/ugenis7.github.io/
baseurl:          https://ugenis7.github.io/

author:
  name:           'Ulises Genis Cuevas'
  url:            https://twitter.com/ugenis7

paginate:         5
